- name: install packages
  apt: 
    name: 
      - curl
      - git
      - htop
      - ipcalc
      - iperf3
      - ipython3
      - mc
      - ncdu
      - neofetch
      - net-tools
      - netcat
      - nginx
      - nmap
      - ntopng
      - openssh-server
      - python3-pip
      - ranger
      - tcpdump
      - tmux
      - traceroute
      - vpnc
      - zsh
